import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { PopupWidget }  from "@/components/PopupWidget";
import AnimatedPageWrapper from "@/components/AnimatedPageWrapper";
import { CartProvider } from '../components/CartContext';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <ThemeProvider attribute="class">
            <Navbar />
            <AnimatedPageWrapper>{children}</AnimatedPageWrapper>
            <Footer />
            <PopupWidget />
          </ThemeProvider>
        </CartProvider>
      </body>
    </html>
  );
}
